<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404</title>

    <link rel="stylesheet" href="./vendor/css/style.css">
</head>

<body>
    <main>
        <section class="error-404">
            <img src="./vendor/images/logo-dark.png" alt="Brand Logo">
            <p>ERREUR 404</p>
            <h1>Oups....cette page n'existe pas !</h1>
            <a href="./index.php?page=Accueil">
                <button class="btn">Retour à l'accueil</button>
            </a>
        </section>
    </main>
</body>

</html>