<main>
    <section class="services__option">
        <h1>Achat-Vente</h1>
        <article class="services__option--display">
            <div>
                <h3>Textiles, accessoires, chaussures</h3>
                <p>Nous vendons et rachetons tous types de vêtements, chaussures et accessoires, tant qu'ils sont encore utilisables ou portables.</p>
            </div>
            <img class="services__option__img" src="./vendor/images/apparel-gee6a96712_1280.jpg" alt="Achat-Vente">
        </article>
    </section>
    <section class="services__option">
        <h1>Couture</h1>
        <article class="services__option--display">
            <img class="services__option__img" src="./vendor/images/sewing-g83e1335c3_1280.jpg" alt="Service couture">    
            <div>
                <p>Ourlets : prenez rendez-vous afin que nous nous occupions de vos ourlets</p>
                <p>Modification de pièces : Vous voulez transformer vos vêtements, ou même un rideau ? Nous serons là pour réaliser vos souhaits.</p>
                <p>Reprise de tailles</p>
            </div>
        </article>
    </section>
    <section class="services__option">
        <h1>Frip' à domicile</h1>
        <article>
            <h3>Camion ambulant <em>(Coming soon...)</em></h3>
            <img class="truck" src="./vendor/images/truck.svg" alt="truck">
            <h3>Vente et rachat chez le particulier</h3>
                <p>Nous nous déplacons directement à votre domicile pour vous présenter notre stock (en fonction de vos souhaits), mais aussi pour racheter ce que vous ne voulez plus garder. Prise de rendez-vous ci-dessous :</p>
                <div class="calendar calendly-inline-widget" data-url="https://calendly.com/dfripetvous"></div>
                <script src="https://assets.calendly.com/assets/external/widget.js" async></script>
        </article>
    </section>
    <section class="services__option">
        <h1>Carte de Frip'élité</h1>
        <article>
            <p>Remises sur le service couture</p>
            <p>Remises sur la vente de vêtements à chaque date anniversaire (date de naissance et date d'inscription)</p>
        </article>
    </section>
</main>